import turtle as trtl
import random

painter = trtl.Turtle()
def house():
    painter.begin_fill()
    turn_number = 0
    painter.forward(200)
    painter.right(90)
    painter.forward(400)
    turn_number +=1
    painter.right(90)
    painter.forward(300)
    door_turns = 0
    while door_turns < 4:
        painter.right(90)
        painter.forward(200)
        door_turns += 1
    painter.forward(100)
    turn_number = 0
    while turn_number < 2:
        painter.right(90)
        painter.forward(400)
        turn_number +=1
    painter.fillcolor("orange")
    painter.end_fill()
    painter.begin_fill()
    painter.fillcolor("brown")
    painter.goto(0, 210)
    painter.goto(-200, 0)
    painter.end_fill()
def family(member_name):
    painter.begin_fill()
    painter.fillcolor("beige")
    if member_name == "Dad" or member_name == "Mom":
        painter.circle(50)
        painter.end_fill()
        painter.right(90)
        painter.forward(75)
        painter.right(90)
        painter.forward(50)
        painter.right(180)
        painter.forward(100)
        painter.right(180)
        painter.forward(50)
        painter.right(-90)
        painter.forward(75)
        painter.goto(painter.xcor() - 50, painter.ycor() - 100)
        painter.goto(painter.xcor() + 50, painter.ycor() + 100)
        painter.goto(painter.xcor() + 50, painter.ycor() - 100)
    elif member_name == "Daughter":
        painter.circle(40)
        painter.end_fill()
        painter.right(90)
        painter.forward(50)
        painter.right(90)
        painter.forward(50)
        painter.right(180)
        painter.forward(100)
        painter.right(180)
        painter.forward(50)
        painter.right(-90)
        painter.forward(75)
        painter.goto(painter.xcor() - 50, painter.ycor() - 75)
        painter.goto(painter.xcor() + 50, painter.ycor() + 75)
        painter.goto(painter.xcor() + 50, painter.ycor() - 75)
def mustang():
    painter.begin_fill()
    painter.fillcolor("brown")
    painter.circle(75)
    painter.penup()
    painter.hideturtle()
    painter.goto(-450, -175)
    painter.right(90)
    painter.showturtle()
    painter.pendown()
    painter.forward(200)
    painter.right(-90)
    painter.forward(50)
    painter.right(-90)
    painter.forward(100)
    painter.right(180)
    painter.forward(100)
    painter.right(-90)
    painter.forward(50)
    painter.right(-90)
    painter.forward(100)
    painter.right(90)
    painter.forward(50)
    painter.right(90)
    painter.forward(100)
    painter.right(-90)
    painter.forward(50)
    painter.right(-90)
    painter.forward(200)
    painter.right(-90)
    painter.forward(100)
    painter.end_fill()
    painter.begin_fill()
    painter.penup()
    painter.hideturtle()
    painter.goto(-465.5, -75)
    painter.right(90)
    painter.showturtle()
    painter.pendown()
    painter.goto(-440, -25)
    painter.right(180)
    painter.goto(-400, -75)
    painter.end_fill()
    painter.begin_fill()
    painter.penup()
    painter.hideturtle()
    painter.goto(-395, -75)
    painter.right(90)
    painter.showturtle()
    painter.pendown()
    painter.goto(-365, -25)
    painter.right(180)
    painter.goto(-340, -75)
    painter.end_fill()
    painter.begin_fill()
    painter.fillcolor("black")
    painter.penup()
    painter.hideturtle()
    painter.goto(-350, -50)
    painter.showturtle()
    painter.pendown()
    turn_number = 0
    while turn_number < 2:
        painter.right(90)
        painter.forward(50)
        painter.right(90)
        painter.forward(125)
        turn_number += 1
    painter.end_fill()
    painter.penup()
    painter.hideturtle()
    painter.goto(-250, -150)
    painter.begin_fill()
    painter.fillcolor("black")
    painter.showturtle()
    painter.pendown()
    turn_number = 0
    while turn_number < 2:
        painter.right(90)
        painter.forward(30)
        painter.right(90)
        painter.forward(75)
        turn_number += 1
    painter.end_fill()
    painter.penup()
    painter.hideturtle()
    painter.goto(-250, -175)
    painter.begin_fill()
    painter.fillcolor("brown")
    painter.showturtle()
    painter.pendown()
    painter.right(-90)
    turn_number = 0
    while turn_number < 2:
        painter.right(90)
        painter.forward(25)
        painter.right(90)
        painter.forward(150)
        turn_number += 1
    painter.end_fill()
    painter.right(180)
    painter.forward(150)
    painter.begin_fill()
    painter.fillcolor("black")
    painter.circle(25)
    painter.end_fill()
def sun():
    painter.penup()
    painter.hideturtle()
    painter.goto(300, 200)
    painter.begin_fill()
    painter.fillcolor("yellow")
    painter.showturtle()
    painter.pendown()
    painter.circle(100)
    painter.end_fill()
trtl.bgcolor("skyblue")
painter.speed(50)
house()
painter.penup()
painter.hideturtle()
painter.goto(300, -150)
painter.showturtle()
painter.pendown()
family("Dad")
painter.penup()
painter.hideturtle()
painter.goto(450, -150)
painter.right(-90)
painter.showturtle()
painter.pendown()
family("Mom")
painter.penup()
painter.hideturtle()
painter.goto(375, -200)
painter.right(-90)
painter.showturtle()
painter.pendown()
family("Daughter")
painter.penup()
painter.hideturtle()
painter.goto(-400, -200)
painter.right(-90)
painter.showturtle()
painter.pendown()
mustang()
sun()
trtl.done()
